#!/bin/sh -e

APP_NAME="_APP_NAME_"
APP_SAFE_NAME="_APP_SAFE_NAME_"

# Source debconf library.
. /usr/share/debconf/confmodule

db_input high ${APP_NAME}/svn-dav/autoinstall || true
db_go

db_get ${APP_NAME}/svn-dav/autoinstall
if [ "$RET" = "false" ]; then
  exit 0
fi

db_input medium ${APP_NAME}/svn-dav/repositories || true
db_go

db_input low ${APP_NAME}/svn-dav/api-key || true
db_go

db_get ${APP_NAME}/svn-dav/api-key
if [ "$RET" = "" ]; then
  random_key=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c32;echo;)
  db_set ${APP_NAME}/svn-dav/api-key "${random_key}"
fi

