#!/bin/bash

set -ex

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

APP_NAME="_APP_NAME_"
CLI="${APP_NAME}"

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in

  configure)

    db_get ${APP_NAME}/svn-dav/autoinstall

    if [ "$RET" = "false" ]; then
      rm -f "/etc/${APP_NAME}/conf.d/svn-dav"
      rm -f "/etc/${APP_NAME}/apache2/svn-perl.conf"
      rm -f "/etc/${APP_NAME}/apache2/vhost/svn.conf"

      exit 0
    else
      db_get ${APP_NAME}/svn-dav/repositories || true
      svn_repositories="$RET"

      if [ ! -d "$svn_repositories" ]; then
	mkdir -p "$svn_repositories"
	chown ${APP_NAME}.${APP_NAME} "$svn_repositories"
      fi

      echo "export SVN_REPOSITORIES=\"${svn_repositories}\"" > /etc/${APP_NAME}/conf.d/svn-dav

      port=$(${CLI} config:get PORT || echo "6000")

      # set SYS_API_KEY, the OpenProject API key
      sys_api_key_random=$(< /dev/urandom tr -dc a-z0-9 | head -c32;echo;)
      sys_api_key=$(${CLI} config:get SYS_API_KEY || echo "${sys_api_key_random}")
      ${CLI} config:set SYS_API_KEY="${sys_api_key}"

      # copy OpenProject perl script for authentication
      cp -f "/opt/${APP_NAME}/extra/svn/OpenProjectAuthentication.pm" /usr/lib/perl5/Apache/
      echo "PerlLoadModule Apache::OpenProjectAuthentication" > "/etc/${APP_NAME}/apache2/svn-perl.conf"

      # generates the apache configuration to allow for checking out SVN repositories
      src="/usr/share/${APP_NAME}-svn-dav/templates/includes/vhost/svn.conf"
      dst="/etc/${APP_NAME}/apache2/vhost/svn.conf"
      tmpfile=$(mktemp)
      cp -f "$src" "$tmpfile"
      sed -i "s|_SVN_REPOSITORIES_|${svn_repositories}|g" ${tmpfile}
      sed -i "s|_APP_URI_|http://127.0.0.1:${port}|g" ${tmpfile}
      sed -i "s|_APP_API_KEY_|${sys_api_key}|g" ${tmpfile}
      mv -f "$tmpfile" "$dst"
      chmod 0640 "$dst"

      # reload apache reconfiguration
      service apache2 reload || true

    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

